# Generated by Django 3.1.4 on 2021-01-30 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_farm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('built_year', models.DateField(auto_now=True)),
                ('depth', models.FloatField(default=0)),
                ('diameter', models.FloatField(default=0)),
                ('material', models.BooleanField(default=True)),
                ('area', models.FloatField(default=0)),
                ('label', models.FloatField(default=0)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.farm')),
            ],
        ),
    ]
