# Generated by Django 3.1.4 on 2021-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_well'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='built_year',
            field=models.IntegerField(),
        ),
    ]
