# Generated by Django 3.1.4 on 2021-02-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210130_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='built_year',
            field=models.IntegerField(default=0),
        ),
    ]
