# Generated by Django 3.1.4 on 2021-02-21 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_muster'),
    ]

    operations = [
        migrations.AddField(
            model_name='muster',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
