# Generated by Django 3.1.4 on 2021-03-05 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusterPumping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_pumping', models.TimeField(default=django.utils.timezone.now)),
                ('finishing_pumping', models.TimeField(default=django.utils.timezone.now)),
                ('count_gall', models.IntegerField(default=0)),
                ('size_gall', models.FloatField(default=0)),
                ('ugv_before_pumping', models.FloatField(default=0)),
                ('ugv_after_pumping', models.FloatField(default=0)),
                ('bottom', models.FloatField(default=0)),
                ('speed_water', models.FloatField(default=0)),
                ('elevated', models.FloatField(default=0)),
                ('reduced', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well')),
            ],
        ),
        migrations.DeleteModel(
            name='Muster',
        ),
    ]
