# Generated by Django 3.1.4 on 2021-06-08 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0012_auto_20210307_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='district',
        ),
        migrations.AddField(
            model_name='position',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AddField(
            model_name='staff',
            name='districts',
            field=models.ManyToManyField(to='main.District'),
        ),
    ]
