# Generated by Django 3.1.4 on 2021-06-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210608_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
