# Generated by Django 3.1.4 on 2021-06-17 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_staff_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='priority',
        ),
    ]
