# Generated by Django 3.1.4 on 2021-06-30 05:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_position_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ugv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well')),
            ],
        ),
        migrations.CreateModel(
            name='Mgv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.FloatField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
                ('well', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well')),
            ],
        ),
    ]
