# Generated by Django 3.1.4 on 2021-11-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20211122_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildeep',
            name='mustersoil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mustersoil'),
        ),
    ]
