# Generated by Django 3.1.4 on 2021-11-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_soildeep_mustersoil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysissoil',
            old_name='mustersoil',
            new_name='muster_soil',
        ),
        migrations.RenameField(
            model_name='mustersoil',
            old_name='croptype',
            new_name='crop_type',
        ),
        migrations.RenameField(
            model_name='soildeep',
            old_name='mustersoil',
            new_name='muster_soil',
        ),
        migrations.RenameField(
            model_name='soildeep',
            old_name='soiltype',
            new_name='soil_type',
        ),
    ]
