# Generated by Django 3.1.4 on 2021-11-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20211126_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildeep',
            name='muster_soil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.mustersoil'),
        ),
    ]
