# Generated by Django 3.1.4 on 2022-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220130_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFakeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_report', 'Reporting rights'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
