# Generated by Django 3.1.4 on 2022-03-02 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220221_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ugv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 2, 12, 52, 50, 932080)),
        ),
        migrations.CreateModel(
            name='YieldSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0)),
                ('year', models.DateField(default=datetime.date.today)),
                ('cropt_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.croptype')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district')),
                ('salt_degree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.saltdegree')),
            ],
        ),
        migrations.CreateModel(
            name='WaterSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0)),
                ('year', models.DateField(default=datetime.date.today)),
                ('cropt_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.croptype')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district')),
            ],
        ),
        migrations.CreateModel(
            name='WaterNorm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(default=0)),
                ('year', models.DateField(default=datetime.date.today)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.district')),
            ],
        ),
    ]
