# Generated by Django 3.1.4 on 2022-04-05 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20220302_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='musterpumping',
            name='water_salinity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ugv',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 11, 48, 51, 181677)),
        ),
    ]
